/**
 * Environment variable generator for env-secure.
 * Extracts env vars from scanned secrets and generates .env.example files.
 */

import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import { ScanResult } from './scanner.js';

export interface EnvVarEntry {
  key: string;
  value: string;
  description: string;
  required: boolean;
}

const KNOWN_ENV_DESCRIPTIONS: Record<string, string> = {
  // Cloud
  AWS_ACCESS_KEY_ID: 'AWS IAM access key ID',
  AWS_SECRET_ACCESS_KEY: 'AWS IAM secret access key',
  GOOGLE_API_KEY: 'Google Cloud API key',
  GOOGLE_CLIENT_ID: 'Google OAuth client ID',
  GOOGLE_CLIENT_SECRET: 'Google OAuth client secret',
  DIGITALOCEAN_TOKEN: 'DigitalOcean personal access token',
  HEROKU_API_KEY: 'Heroku API key',
  VERCEL_TOKEN: 'Vercel deployment token',
  NETLIFY_AUTH_TOKEN: 'Netlify personal access token',
  AZURE_STORAGE_KEY: 'Azure storage account key',

  // Version Control
  GITHUB_TOKEN: 'GitHub personal access token',
  GITHUB_APP_TOKEN: 'GitHub app installation token',
  GITLAB_TOKEN: 'GitLab personal access token',

  // Payments
  STRIPE_SECRET_KEY: 'Stripe secret key (live/test)',
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'Stripe publishable key',
  STRIPE_WEBHOOK_SECRET: 'Stripe webhook signing secret',
  SHOPIFY_ACCESS_TOKEN: 'Shopify admin API access token',
  PAYPAL_CLIENT_SECRET: 'PayPal REST API client secret',

  // Communication
  SLACK_BOT_TOKEN: 'Slack bot user OAuth token',
  SLACK_ACCESS_TOKEN: 'Slack workspace access token',
  SLACK_WEBHOOK_URL: 'Slack incoming webhook URL',
  DISCORD_BOT_TOKEN: 'Discord bot token',
  TWILIO_ACCOUNT_SID: 'Twilio account SID',
  TWILIO_AUTH_TOKEN: 'Twilio auth token',

  // Email
  SENDGRID_API_KEY: 'SendGrid API key for email sending',
  MAILGUN_API_KEY: 'Mailgun API key',
  MAILCHIMP_API_KEY: 'Mailchimp API key',
  POSTMARK_TOKEN: 'Postmark server API token',
  RESEND_API_KEY: 'Resend API key for transactional emails',

  // Database
  MONGODB_URI: 'MongoDB connection string',
  DATABASE_URL: 'PostgreSQL database connection string',
  MYSQL_URL: 'MySQL database connection string',
  REDIS_URL: 'Redis connection string',
  NEXT_PUBLIC_SUPABASE_URL: 'Supabase project URL',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'Supabase anonymous API key',

  // Auth
  JWT_SECRET: 'JWT signing secret (generate a random 64-char string)',
  NPM_TOKEN: 'npm registry authentication token',
  DOCKER_AUTH: 'Docker registry authentication',
  CLERK_SECRET_KEY: 'Clerk secret key',
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'Clerk publishable key',
  AUTH0_CLIENT_SECRET: 'Auth0 application client secret',

  // Monitoring
  NEXT_PUBLIC_SENTRY_DSN: 'Sentry DSN for error tracking',
  DATADOG_API_KEY: 'Datadog API key',
};

/**
 * Build a list of unique env var entries from scan results.
 */
export function extractEnvEntries(results: ScanResult[]): EnvVarEntry[] {
  const envMap = new Map<string, EnvVarEntry>();

  for (const result of results) {
    if (result.pattern.envVar) {
      const name = result.pattern.envVar;
      if (!envMap.has(name)) {
        envMap.set(name, {
          key: name,
          value: 'your_value_here',
          description: KNOWN_ENV_DESCRIPTIONS[name] || `${result.pattern.category} ${result.pattern.name}`,
          required: result.pattern.confidence === 'high',
        });
      }
    }
  }

  // Sort: required first, then alphabetical
  return Array.from(envMap.values()).sort((a, b) => {
    if (a.required !== b.required) return a.required ? -1 : 1;
    return a.key.localeCompare(b.key);
  });
}

/**
 * Generate .env.example content from env entries.
 */
export function generateEnvExample(entries: EnvVarEntry[]): string {
  const lines: string[] = [];
  
  lines.push('# ─────────────────────────────────────────────────────────');
  lines.push('# 🔐 Environment Variables');
  lines.push(`# Generated by env-secure on ${new Date().toISOString().split('T')[0]}`);
  lines.push('# Copy this file to .env.local and fill in your values');
  lines.push('# ─────────────────────────────────────────────────────────');
  lines.push('');

  // Group by whether they start with NEXT_PUBLIC_
  const publicVars = entries.filter(e => e.key.startsWith('NEXT_PUBLIC_'));
  const privateVars = entries.filter(e => !e.key.startsWith('NEXT_PUBLIC_'));

  if (privateVars.length > 0) {
    lines.push('# ─── Server-side (keep private) ────────────────────────');
    for (const entry of privateVars) {
      const comment = entry.description ? `# ${entry.description}` : '';
      lines.push(comment);
      const value = entry.required ? entry.value : `# ${entry.key}=${entry.value}`;
      if (!entry.required) {
        lines.push(`# ${entry.key}=`);
      } else {
        lines.push(`${entry.key}=${entry.value}`);
      }
      lines.push('');
    }
  }

  if (publicVars.length > 0) {
    lines.push('# ─── Client-side (safe for browser) ───────────────────');
    for (const entry of publicVars) {
      const comment = entry.description ? `# ${entry.description}` : '';
      lines.push(comment);
      lines.push(`${entry.key}=${entry.value}`);
      lines.push('');
    }
  }

  // Add common required vars if not already present
  const existingKeys = new Set(entries.map(e => e.key));
  const commonVars: EnvVarEntry[] = [
    { key: 'NODE_ENV', value: 'development', description: 'Node environment', required: true },
    { key: 'PORT', value: '3000', description: 'Application port', required: true },
    { key: 'APP_URL', value: 'http://localhost:3000', description: 'Application base URL', required: true },
  ];

  const missingCommon = commonVars.filter(v => !existingKeys.has(v.key));
  if (missingCommon.length > 0) {
    lines.push('# ─── General ──────────────────────────────────────────');
    for (const entry of missingCommon) {
      const comment = entry.description ? `# ${entry.description}` : '';
      lines.push(comment);
      lines.push(`${entry.key}=${entry.value}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Write .env.example to disk.
 */
export function writeEnvExample(entries: EnvVarEntry[], outputDir: string): string {
  const content = generateEnvExample(entries);
  const outputPath = join(outputDir, '.env.example');
  writeFileSync(outputPath, content, 'utf-8');
  return outputPath;
}

/**
 * Merge scan results with existing .env.example if it exists.
 */
export function mergeWithExisting(entries: EnvVarEntry[], existingPath: string): EnvVarEntry[] {
  try {
    const existing = readFileSync(existingPath, 'utf-8');
    const existingKeys = new Set(
      existing
        .split('\n')
        .filter(l => l.includes('=') && !l.startsWith('#'))
        .map(l => l.split('=')[0].trim())
    );

    // Merge: keep existing entries, add new ones from scan
    const merged = new Map<string, EnvVarEntry>();
    for (const e of entries) merged.set(e.key, e);

    for (const line of existing.split('\n')) {
      if (line.includes('=') && !line.startsWith('#')) {
        const [key, ...valParts] = line.split('=');
        const keyTrimmed = key.trim();
        if (keyTrimmed && !merged.has(keyTrimmed)) {
          merged.set(keyTrimmed, {
            key: keyTrimmed,
            value: valParts.join('=').trim(),
            description: '',
            required: true,
          });
        }
      }
    }

    return Array.from(merged.values()).sort((a, b) => {
      if (a.required !== b.required) return a.required ? -1 : 1;
      return a.key.localeCompare(b.key);
    });
  } catch {
    return entries;
  }
}
